title: "Kazuki Kumashiro"
tagline: ""
description: "Personal academic website"
url: "https://k-kumashiro.github.io"
baseurl: ""

accent_image: /assets/img/menu_bg.png
favicon: /assets/img/favicon.png
google_analytics: G-NSKPC8JX50
google_site_verification: "l8qWnEC3Uiuh7rAwXRRg37OTLyAoY70tF5fJksBO79M"

remote_theme: hydecorp/hydejack@v9

legal:
  - title: Privacy Policy
    url: /privacy/

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

author:
  name: "Kazuki Kumashiro"
  email: 

menu:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/
  - title: CV
    url: /cv/

hydejack:
  no_blog: true
  no_search: true
