title: "Kazuki Kumashiro"
tagline: ""
description: ""
url: "https://k-kumashiro.github.io"
baseurl: "/website"

remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

author:
  name: "Kazuki Kumashiro"
  email: 

menu:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/
  - title: CV
    url: /cv/

hydejack:
  no_blog: true
  no_search: true
